# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'bundler'
gem 'sinatra'
gem 'omniauth'
# gem 'omniauth-uaa-oauth2', git: 'https://github.com/drnic/omniauth-uaa-oauth2', branch: 'avoid-deprecation-warning'
gem 'omniauth-uaa-oauth2', path: '/Users/drnic/Projects/uaa/omniauth-uaa-oauth2'
gem 'cf-uaa-lib', path: '/Users/drnic/Projects/uaa/cf-uaa-lib'

group :development do
  gem 'shotgun'
end